travis:
  secure:
    BINSTAR_TOKEN: XeEvdvPZwGm82P9onZprzlMwrb4ODmUXmTFsohZx+HQUM6Ytj59iEGDCATvzYd44MLbFEHf2bvYtF0OCeT4vpyH3pjeEfPy9jxXaiRzqmicnfuiWHGhLhMnTFVCDqtB9Nx1xAb2easRSg1X/R0QEudEHmRrEiGv3PvjCzCXnEdNPLQM5inSErPDO2Z/F3JIisUPVGxfS7yiWKvTl00IOKjMDUEkGQ7yHht75JV+IHV9TT5JIWb+mfuOhYDLbsND/Lw0km0bXx4EEZE8cAlJ3zLSeVVJ7QsVorx8Yij7SfGZWzqayGF6av0LnVt0N+y7GzYVv5JtfUiEm436Sk3VDJT66qWrMj8w9qU7j5vj2WKGgWoEX9XrNCCai9FFtZ8EQkuFG3i35zUQHHo9lDgcdZzaNoFOQ5xWodEEW6/D09O0oNJOCq+ZOvnByJLwtoTs44+Q8n6wVftWAmvsbEfLdfftr/tozKSsRD8uVvNH5hqboaKr65A+FQczc+l2lo5LLqTSaAisPnhTUl9vqZSzd3wVKSgbxwNpIcFyrMnaMH8HowDCyWtFgShCIIf4Ghaw73vd/IQ1vjjl4h97yGbxDtSYxc+ccc2VSspjoLFSOg6LdfOcuH+4QNnb198FqwfjjAmo06J2Qq6NORySgwPx5aIq5Ps2Yl1YsGErhKRkGhyI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
conda_forge_output_validation: true
