travis:
  secure:
    BINSTAR_TOKEN: XByl3F8EazjMJc9lzIb+BdjYzn3O08/lPs0v5QFPEoMW0qSl6FupCk1rrCaFe3PtJTYGTSKQ4bpw0Pz/biwrayuR2/L2U/QVYdapsKHJXyjXFPcGkvsdIBw+mdwbo/gjc1LVx5A3nYV2lHcqBoVaW44YGH6pI/vSxAhGHt1LNhAHT1DDphpsSHdR0diY4nDjKbBfQp1OMlN2PV5Rk9/sxHn3QYML+WTAeg7qnPFXRaXdIQ/sDHLYibXqzwaHRB969KEi7L6+gWngp12cP5FIj9n5HHM+xMgL4MBfJ+1NWFix/LlHBu9JeXERy3o5nQDP8Lq6475M2PJNNSw+qcqQGrYYbZFHHrPswe48dGl6h84CUHJz43BhyJO6cfEW4CKYInTfGNEtoNkCf/ztOjA4QunUvTgOfXZs1ywKM4mRmJ3rVzI6PQzH77QXrLHdyZGiuHI1W+gS8dH7A3r5Ub98PIEtofpPxVcSGV6BRpf+BL3WjjF1IqmCfEQt8ZrAxacR7bDiW/HO89FGZ/9YHxELuKSjP4w6C+0tP2n7hnlG3pOSaiQQ+kJz2RTeOQk0y6WbrgTT8lTo4FcQwyM5wUr8YinIEsBrIytJRCkfqnLKmXStsPO5fAstXWiFQEy/5eVq9sXheErHKDHnRD6Yl89wksI868zQmEGVAV7VTSujl7w=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
